/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#00daf3',
        'primary-container': '#ff5a8f',
        'on-tertiary': '#00363d',
        'on-surface-variant': '#dfbec4',
        'on-tertiary-fixed': '#001f24',
        'tertiary-container': '#00a5b8',
        'tertiary': '#00daf3',
        'surface-container': '#201f21',
        'surface-container-highest': '#353437',
        'on-error': '#690005',
        'inverse-on-surface': '#303032',
        'inverse-surface': '#e5e1e4',
        'on-secondary-container': '#c0acff',
        'on-background': '#e5e1e4',
        'on-secondary-fixed-variant': '#4f00d0',
        'on-primary-container': '#63002b',
        'inverse-primary': '#b41d58',
        'surface-container-low': '#1b1b1d',
        'on-tertiary-fixed-variant': '#004f58',
        'surface-variant': '#353437',
        'outline-variant': '#584045',
        'on-primary-fixed-variant': '#8f0041',
        'surface-container-lowest': '#0e0e10',
        'on-secondary': '#370096',
        'error': '#ffb4ab',
        'primary': '#ffb1c3',
        'surface-bright': '#39393b',
        'on-surface': '#e5e1e4',
        'error-container': '#93000a',
        'surface-tint': '#ffb1c3',
        'primary-fixed-dim': '#ffb1c3',
        'secondary-fixed-dim': '#cdbdff',
        'surface-container-high': '#2a2a2c',
        'background': '#131315',
        'on-primary': '#66002c',
        'outline': '#a7898f',
        'surface': '#131315',
        'on-tertiary-container': '#00343b',
        'secondary-fixed': '#e8deff',
        'secondary': '#cdbdff',
        'on-secondary-fixed': '#20005f',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffd9e0',
        'on-primary-fixed': '#3f0019',
        'surface-dim': '#131315',
        'secondary-container': '#5203d5',
        'tertiary-fixed': '#9cf0ff',
      },
      borderRadius: {
        'DEFAULT': '1rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
      },
      fontFamily: {
        'headline': ['Plus Jakarta Sans', 'sans-serif'],
        'body': ['Manrope', 'sans-serif'],
        'label': ['Plus Jakarta Sans', 'sans-serif'],
      },
      boxShadow: {
        'glow-primary': '0 20px 50px rgba(255, 90, 143, 0.15)',
        'glow-secondary': '0 20px 50px rgba(82, 3, 213, 0.15)',
      },
      animation: {
        'float-slow': 'float 4s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
      },
    },
  },
  plugins: [],
}
